//! `holocron` - CLI for training the engine and asking natural-language questions.

use std::io::Read;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use comfy_table::{Cell, Table};
use tracing::Instrument;

use holocron_core::logging::{self, Format};
use holocron_core::{default_engine, Config, Engine, QueryResult, TrainingItem};

#[derive(Parser)]
#[command(name = "holocron", about = "Text-to-SQL over your Postgres, powered by Gemini + RAG")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Create the pgvector extension, training table, and index.
    InitDb,

    /// Add training material (schema DDL, docs, or a question/SQL pair).
    Train(TrainArgs),

    /// Ask a natural-language question. Generates SQL; `--run` also executes it
    /// and phrases the result back into a written answer.
    Ask {
        question: String,
        /// Execute the generated SQL and print the result table.
        #[arg(long)]
        run: bool,
        /// With `--run`, skip the natural-language answer over the results.
        #[arg(long)]
        no_answer: bool,
        /// Also suggest follow-up questions.
        #[arg(long)]
        followups: bool,
        /// Emit JSON instead of pretty tables.
        #[arg(long)]
        json: bool,
    },

    /// Run a SQL statement directly against the warehouse.
    Run {
        sql: String,
        #[arg(long)]
        json: bool,
    },

    /// List stored training material.
    List,

    /// Remove one training row by id.
    Remove { id: String },
}

#[derive(clap::Args)]
struct TrainArgs {
    /// DDL text, a file path, or `-` for stdin.
    #[arg(long)]
    ddl: Option<String>,
    /// Documentation text, a file path, or `-` for stdin.
    #[arg(long)]
    doc: Option<String>,
    /// SQL text, a file path, or `-` for stdin.
    #[arg(long)]
    sql: Option<String>,
    /// Question paired with `--sql`. If omitted, one is generated by the LLM.
    #[arg(long)]
    question: Option<String>,
    /// Auto-train from the warehouse's information_schema.
    #[arg(long)]
    auto: bool,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let config = Config::load().context("failed to load holocron.toml")?;
    // Logging in the shared DairyBook `./api` style, configured from config.
    let span = logging::init_service(&config.log_level, Format::parse(&config.log_format), "holocron-cli");

    async move {
    let engine = default_engine(config)
        .await
        .context("failed to initialize engine")?;

    match cli.command {
        Command::InitDb => {
            // default_engine already ran init_db.
            tracing::info!("database schema initialized");
            println!("Database initialized (training_data table + hnsw index ready).");
        }

        Command::Train(args) => train(&engine, args).await?,

        Command::Ask { question, run, no_answer, followups, json } => {
            // Running produces rows to answer over; `--no-answer` opts out.
            let answer = run && !no_answer;
            tracing::debug!(%question, run, answer, followups, "ask");
            let result = engine.ask(&question, run, answer, followups).await?;
            if json {
                println!("{}", serde_json::to_string_pretty(&result)?);
            } else {
                println!("\n-- SQL --\n{}\n", result.sql);
                if let Some(err) = &result.error {
                    println!("Execution error: {err}");
                }
                if let Some(qr) = &result.result {
                    print_result(qr);
                }
                if let Some(answer) = &result.answer {
                    println!("\n-- Answer --\n{answer}");
                }
                if !result.followups.is_empty() {
                    println!("\nFollow-up questions:");
                    for f in &result.followups {
                        println!("  • {f}");
                    }
                }
            }
        }

        Command::Run { sql, json } => {
            tracing::debug!("run raw SQL");
            let qr = engine.run_sql(&sql).await?;
            if json {
                println!("{}", serde_json::to_string_pretty(&qr)?);
            } else {
                print_result(&qr);
            }
        }

        Command::List => {
            let rows = engine.list_training().await?;
            let mut table = Table::new();
            table.set_header(vec!["id", "kind", "question", "content"]);
            for r in rows {
                table.add_row(vec![
                    Cell::new(&r.id),
                    Cell::new(r.kind.as_str()),
                    Cell::new(r.question.as_deref().unwrap_or("")),
                    Cell::new(truncate(&r.content, 80)),
                ]);
            }
            println!("{table}");
        }

        Command::Remove { id } => {
            let removed = engine.remove_training(&id).await?;
            println!("{}", if removed { "Removed." } else { "No such id." });
        }
    }

        Ok(())
    }
    .instrument(span)
    .await
}

async fn train(engine: &Engine, args: TrainArgs) -> Result<()> {
    if args.auto {
        let n = engine.train_from_information_schema().await?;
        println!("Trained {n} table(s) from information_schema.");
    }
    if let Some(src) = args.ddl {
        let ddl = read_source(&src)?;
        let id = engine.train(TrainingItem::Ddl { ddl }).await?;
        println!("Added DDL ({id}).");
    }
    if let Some(src) = args.doc {
        let documentation = read_source(&src)?;
        let id = engine.train(TrainingItem::Documentation { documentation }).await?;
        println!("Added documentation ({id}).");
    }
    if let Some(src) = args.sql {
        let sql = read_source(&src)?;
        let id = engine
            .train(TrainingItem::Sql { question: args.question, sql })
            .await?;
        println!("Added question/SQL pair ({id}).");
    }
    Ok(())
}

/// Interpret a training source: `-` = stdin, an existing path = file contents,
/// otherwise the literal string.
fn read_source(src: &str) -> Result<String> {
    if src == "-" {
        let mut buf = String::new();
        std::io::stdin().read_to_string(&mut buf)?;
        Ok(buf)
    } else if std::path::Path::new(src).is_file() {
        std::fs::read_to_string(src).with_context(|| format!("reading {src}"))
    } else {
        Ok(src.to_string())
    }
}

fn print_result(qr: &QueryResult) {
    let mut table = Table::new();
    if !qr.columns.is_empty() {
        table.set_header(qr.columns.iter().map(Cell::new));
    }
    for row in &qr.rows {
        table.add_row(row.iter().map(|v| Cell::new(render_value(v))));
    }
    println!("{table}");
    println!("({} row(s))", qr.row_count());
}

fn render_value(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Null => String::new(),
        serde_json::Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

fn truncate(s: &str, max: usize) -> String {
    let one_line = s.replace('\n', " ");
    if one_line.chars().count() <= max {
        one_line
    } else {
        let cut: String = one_line.chars().take(max).collect();
        format!("{cut}…")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    #[test]
    fn truncate_collapses_newlines_and_keeps_short_strings() {
        assert_eq!(truncate("a\nb", 80), "a b");
        assert_eq!(truncate("short", 80), "short");
    }

    #[test]
    fn truncate_adds_ellipsis_past_the_limit() {
        assert_eq!(truncate("abcdef", 3), "abc…");
    }

    #[test]
    fn truncate_counts_characters_not_bytes() {
        // A boundary case: exactly `max` chars is not truncated.
        assert_eq!(truncate("abc", 3), "abc");
        assert_eq!(truncate("abcd", 3), "abc…");
    }

    #[test]
    fn render_value_formats_by_json_type() {
        assert_eq!(render_value(&serde_json::Value::Null), "");
        assert_eq!(render_value(&serde_json::json!("hi")), "hi"); // string: no quotes
        assert_eq!(render_value(&serde_json::json!(42)), "42");
        assert_eq!(render_value(&serde_json::json!(true)), "true");
        assert_eq!(render_value(&serde_json::json!({ "a": 1 })), "{\"a\":1}");
    }

    #[test]
    fn read_source_returns_literal_for_non_path() {
        assert_eq!(read_source("CREATE TABLE t (id int)").unwrap(), "CREATE TABLE t (id int)");
    }

    #[test]
    fn read_source_reads_file_contents() {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!("holocron-cli-test-{}-{n}.sql", std::process::id()));
        std::fs::write(&path, "SELECT 1 FROM t").unwrap();
        let got = read_source(path.to_str().unwrap()).unwrap();
        assert_eq!(got, "SELECT 1 FROM t");
        let _ = std::fs::remove_file(&path);
    }
}
